# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r: bioc-release
sudo: required
cache: packages

apt_packages:
  - oracle-java9-installer
  - libxml2-dev
  - libnetcdf-dev
  - netcdf-bin

jdk: oraclejdk9

r_binary_packages:
    - checkmate
    - data.table
    - withr
    - digest
    - XML
    - DBI
    - RSQLite
    - processx
    - rJava
    - rcdk
    - circlize
    - plotly
    - rhandsontable
    - htmlwidgets
    - shiny
    - knitr
    - rmarkdown
    - DT
    - kableExtra
    - R.utils
    - glue
    - ggplot2
    - ggrepel
    - cowplot
    - jsonlite
    - Rdpack
    - igraph
    - Hmisc
    - ff
    - mclust
    - robustbase
    - commonmark

bioc_packages:
    - mzR
    - xcms
    - CAMERA

r_github_packages:
    - cbroeckl/RAMClustR
    - rickhelmus/patRoonData

before_install:
    - wget https://abibuilder.informatik.uni-tuebingen.de/archive/openms/OpenMSInstaller/nightly/OpenMS-2.3.0-Linux.deb
    - sudo apt-get install ./OpenMS-2.3.0-Linux.deb

warnings_are_errors: false

r_build_args: --no-build-vignettes --no-manual
r_check_args: --no-build-vignettes --no-manual

script:
    - |
      R CMD build --no-build-vignettes --no-manual .
      travis_wait 30 R CMD check --no-build-vignettes --no-manual patRoon*tar.gz
