# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r: bioc-release
sudo: required
cache: packages

apt_packages:
  - openjdk-8-jdk
  - libxml2-dev
  - libnetcdf-dev
  - netcdf-bin

jdk: openjdk8

r_binary_packages:
    - checkmate
    - data.table
    - withr
    - digest
    - XML
    - DBI
    - RSQLite
    - processx
    - rJava
    - rcdk
    - circlize
    - plotly
    - rhandsontable
    - htmlwidgets
    - shiny
    - knitr
    - rmarkdown
    - DT
    - kableExtra
    - R.utils
    - glue
    - ggplot2
    - ggrepel
    - cowplot
    - jsonlite
    - Rdpack
    - igraph
    - Hmisc
    - ff
    - mclust
    - robustbase
    - commonmark

bioc_packages:
    - mzR
    - xcms
    - CAMERA

r_github_packages:
    - cbroeckl/RAMClustR@036cdd4
    - rickhelmus/patRoonData

before_install:
    - wget -P ~/ https://abibuilder.informatik.uni-tuebingen.de/archive/openms/OpenMSInstaller/nightly/OpenMS-2.2.0-Linux.deb
    - sudo dpkg -i ~/OpenMS-2.2.0-Linux.deb
    - wget -P ~/ http://msbi.ipb-halle.de/~cruttkie/metfrag/MetFrag2.4.3-CL.jar
    - wget -P ~/ https://bio.informatik.uni-jena.de/repository/dist-release-local/de/unijena/bioinf/ms/sirius/4.0/sirius-4.0-linux64-headless.zip
    - unzip -d ~/ ~/sirius-4.0-linux64-headless.zip
    - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu/ xenial main" -y
    - sudo apt-get update -q
    - sudo apt-get install libfreetype6

warnings_are_errors: false

r_build_args: --no-build-vignettes --no-manual
r_check_args: --no-build-vignettes --no-manual

env:
    global:
        - _R_CHECK_FORCE_SUGGESTS_=0
        - OPENMS_DATA_PATH=/usr/share/OpenMS
        - PATROON_METFRAG=~/MetFrag2.4.3-CL.jar
        - PATROON_SIRIUS=~/sirius-linux64-headless-4.0/bin

script:
    - |
      R CMD build --no-build-vignettes --no-manual .
      travis_wait 30 R CMD check --no-build-vignettes --no-manual patRoon*tar.gz

after_failure:
    - Rscript -e 'options(patRoon.path.metFragCL = "~/MetFrag2.4.3-CL.jar", patRoon.path.SIRIUS = "~/sirius-linux64-headless-4.0/bin"); devtools::install(); devtools::test()' # https://stackoverflow.com/a/45866031/9264518
