# config adapted from https://medium.com/mobileforgood/coding-tips-patterns-for-continuous-integration-with-docker-on-travis-ci-9cedb8348a62
# and https://medium.com/mobileforgood/patterns-for-continuous-integration-with-docker-on-travis-ci-71857fff14c5

sudo: required

services:
  - docker

env:
    - IMAGE_NAME=patroonorg/patroon

before_install:
    - sudo apt-get update
    - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

before_script:
    - docker pull "${IMAGE_NAME}:latest" || true

script:
    - docker build --pull --cache-from "${IMAGE_NAME}:latest" --tag "${IMAGE_NAME}" .

after_script:
    - docker images

before_deploy:
    - docker login -u "$DH_USER" -p "$DH_PASS"
    - git_sha="$(git rev-parse --short HEAD)"
    - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${git_sha}-master"

deploy:
    provider: script
    script: docker push "${IMAGE_NAME}:latest" && docker push "${IMAGE_NAME}:${git_sha}-master"
    on:
        branch: master

notifications:
    email: false

