# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r: bioc-release
sudo: false
cache: packages

addons:
  apt:
    packages:
      - openjdk-8-jdk
      - libxml2-dev
      - libnetcdf-dev
      - netcdf-bin
      - r-cran-rcpp
      - r-cran-stringr
      - r-cran-rjson

jdk: openjdk8

bioc_packages:
    - mzR
    - xcms
    - CAMERA

r_github_packages:
    - cbroeckl/RAMClustR

before_install:
    - wget https://abibuilder.informatik.uni-tuebingen.de/archive/openms/OpenMSInstaller/nightly/OpenMS-2.3.0-Linux.deb
    - dpkg -x OpenMS-2.3.0-Linux.deb OpenMS

warnings_are_errors: false

env:
    global:
        - R_BUILD_ARGS="--no-build-vignettes --no-manual"
        - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"
