# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r: bioc-release
sudo: required
cache: packages

apt_packages:
  - oracle-java9-installer
  - libxml2-dev
  - libnetcdf-dev
  - netcdf-bin

jdk: oraclejdk9

r_binary_packages:
    - checkmate
    - data.table
    - withr
    - digest
    - XML
    - DBI
    - RSQLite
    - processx
    - rJava
    - rcdk
    - circlize
    - plotly
    - rhandsontable
    - htmlwidgets
    - shiny
    - knitr
    - rmarkdown
    - DT
    - kableExtra
    - R.utils
    - glue
    - ggplot2
    - ggrepel
    - cowplot
    - jsonlite
    - Rdpack

bioc_packages:
    - mzR
    - xcms
    - CAMERA

r_github_packages:
    - cbroeckl/RAMClustR

before_install:
    - wget https://abibuilder.informatik.uni-tuebingen.de/archive/openms/OpenMSInstaller/nightly/OpenMS-2.3.0-Linux.deb
    - dpkg -x OpenMS-2.3.0-Linux.deb OpenMS

warnings_are_errors: false

env:
    global:
        - R_BUILD_ARGS="--no-build-vignettes --no-manual"
        - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"
