# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
    - ps: Bootstrap
    - ps: mkdir -Force c:\deps
    - ps: >-
        if (-Not (Test-Path C:\deps\openms.exe)) {
            Invoke-WebRequest https://github.com/OpenMS/OpenMS/releases/download/Release2.3.0/OpenMS-2.3.0-Win64.exe -OutFile "C:\deps\openms.exe"
        }
        C:\deps\openms.exe /S
    - ps: >-
        if (-Not (Test-Path C:\deps\MetFrag2.4.3-CL.jar)) {
            Invoke-WebRequest http://msbi.ipb-halle.de/~cruttkie/metfrag/MetFrag2.4.3-CL.jar -OutFile "C:\deps\MetFrag2.4.3-CL.jar"
        }
    - ps: >-
        if (-Not (Test-Path C:\deps\sirius-win.zip)) {
            Invoke-WebRequest https://bio.informatik.uni-jena.de/repository/dist-release-local/de/unijena/bioinf/ms/sirius/4.0/sirius-4.0-win64-headless.zip -OutFile "C:\deps\sirius-win.zip"
        }
        7z x -oC:\deps\ C:\deps\sirius-win.zip
    #- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

cache:
  - C:\RLibrary
  - C:\Program Files (x86)\Pandoc\
  - C:\deps

# Adapt as necessary starting from here

# Install Pandoc: https://github.com/krlmlr/r-appveyor/issues/82#issuecomment-261695154
before_test:
  - ps: >-
      if (-Not (Test-Path "C:\Program Files (x86)\Pandoc\")) {
        cinst pandoc
      }
  - pandoc -v
  - ps: >-
      if (-Not (Test-Path "C:\ProgramData\chocolatey\bin\pngquant.exe")) {
        cinst pngquant
      }
  - ps: $env:Path += ";C:\Program Files (x86)\Pandoc\"

platform: x64
environment:
    R_ARCH: x64
    BIOC_USE_DEVEL: FALSE
    _R_CHECK_FORCE_SUGGESTS_: 0
    APPVEYOR_SAVE_CACHE_ON_ERROR: true

build_script:
    - travis-tool.sh install_bioc mzR xcms CAMERA
    - travis-tool.sh install_github cbroeckl/RAMClustR@036cdd4
    - travis-tool.sh install_github rickhelmus/patRoonData
    - travis-tool.sh install_github blosloos/nontarget
    - travis-tool.sh install_deps

test_script:
    - set PATH=C:\Program Files\OpenMS-2.3.0\bin;%PATH%
    - set OPENMS_DATA_PATH=C:\Program Files\OpenMS-2.3.0\share\OpenMS
    - set PATROON_METFRAG=C:\deps\MetFrag2.4.3-CL.jar
    - set PATROON_SIRIUS=C:\deps\sirius-win64-headless-4.0
    - travis-tool.sh run_tests

on_failure:
    - 7z a failure.zip *.Rcheck\*
    - appveyor PushArtifact failure.zip

on_finish:
    - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  
artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '..\install.log'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
