version: 2
jobs:
    build:
        working_directory: /app
        docker:
            - image: docker:18.04.0-ce-git
        environment:
            IMAGE_NAME=patroonorg/patroon
        steps:
            - checkout
            - setup_remote_docker:
                docker_layer_caching: true
            - run:
                name: Load Docker image layer cache
                command: |
                    docker pull "${IMAGE_NAME}:latest" || true
            - run:
                name: Build Docker image
                command: |
                    docker build --cache-from "${IMAGE_NAME}:latest" --tag "${IMAGE_NAME}" .
